### ISSUE TITLE
Generation of records beginning with certain number creating garbage values

### ISSUE THREAD

**Issue by schafle** [petergeoghegan/gensort#2]
I am using [gensort](http://www.ordinal.com/try.cgi/gensort-linux-1.5.tar.gz) binary to generate an input file for my sort function.

As per the documentation, following command should generate 1000 records beginning with 2000:

`gensort -b2000 1000 partition2`

This is resulting in creation of 1000 records but are all garbage values.

![gensort_bug](https://cloud.githubusercontent.com/assets/5341407/13907611/073015d6-eec0-11e5-9003-2eb6493193a6.PNG)

**Comment by petergeoghegan** [comment]
I don't maintain gensort; it's only provider here in essentially unchanged form as a convenience to those performance testing PostgreSQL sort stuff. You should take it up with the maintainer.
